config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#main'
  get 'main' => 'pages#main'
  get 'pages/change_subnav'
  get 'pages/change_focus'  
  resources :sessions, only: [:new, :create, :destroy]
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get '/items/:id', to: 'items#show', as: 'item'
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
    resources :users    
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/item.rb
class Item < ActiveRecord::Base
  include Bootsy::Container
  mount_uploader :image, ImageUploader
  has_many :attachments, :as => :attachable, dependent: :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  has_and_belongs_to_many :categories
  validates :name, presence: true
  validates :preview, presence: true
  
  # create a many to many bi-directional association with Items through a join table
  has_many :connections, :foreign_key => "item_id", :class_name => "Connection"
  has_many :connecteds, :through => :connections 

  def connect(item)
    unless self.connecteds.include? item
      self.connecteds << item
      item.connecteds << self
    end
  end
  
  def short_name
    name.truncate(50)
  end
  # provide a slightly nicer url for referencing individual items
  def to_param
    [id, name.parameterize].join("-")
  end
      
  def thumb_geometry
    if image and image.version_exists? :thumb    
      return "#{image_thumb_width}x#{image_thumb_height}"
    else 
      return ""
    end
  end
  
  def video_attachments
    attachments.select {|a| a.is_video_file? }
  end
  
  def doc_attachments
    attachments.select {|a| a.is_doc_file? }    
  end
  
  def image_attachments
    attachments.select {|a| a.is_image_file? }    
  end
    
  def largest_version
    if image_large_height.nil? or image_thumb_height.nil?
      return :empty
    elsif image_large_height > image_thumb_height
      return :large
    else
      return :thumb
    end
  end
  
  def landscape?
    unless image_large_width.nil? or image_large_height.nil?
      if image_large_width > image_large_height
        return true
      else
        return false
      end
    else
      return false
    end
  end
  # uses SQL like to determine if the name or preview text matches the search term
  # TODO fix promoted false issue
  def self.search(search)
    if search
#      includes(:categories, :attachments).where("(name like ? OR preview like ?) AND categories IS NOT NULL", "%#{search}%", "%#{search}%")
      joins(:categories).where("(name like ? OR preview like ?)", "%#{search}%").distinct
    else
      joins(:categories).distinct
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :logged_in?
  layout 'admin'  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all.order("name ASC") #.sort_by {|i| i.send "category.name" rescue ""}
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @categories = Category.find_all_nested
    @connectable_items = Item.all
  end

  # GET /items/1/edit
  def edit  
    @categories = Category.find_all_nested
    @connectable_items = Item.all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @categories = Category.find_all_nested
    respond_to do |format|
      if @item.save
        # add
        format.html { redirect_to admin_items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: [:admin,@item] }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @categories = Category.find_all_nested
    respond_to do |format|
      if @item.update(item_params)
        # add
        format.html { redirect_to admin_items_url, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin,@item] }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to admin_items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :body, :preview, :bootsy_image_gallery_id, :image, :featured, :remove_image, attachments_attributes: [:description, :file, :_destroy, :id], :connected_ids => [], :category_ids => [])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]
  layout 'admin'    
  def show
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end  
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/_form.html.erb
<%= nested_form_for([:admin, @item], :html => {:multipart => true, :role => "form"}) do |f| %>
	<% if @item.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
	    <ul>
	    <% @item.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
  <div class="field form-group">
    <%= f.label :name, class: "control-label" %><br/>
    <%= f.text_field :name, size: 100, class: "form-control" %>
    <span class="help-block">The item's name is required for identification and appears in larger text in any context once it has been selected</span>
  </div>
  <div class="field form-group">
	<%= f.label :categories, class: "control-label"%><br/>
	<%= f.collection_select :category_ids, @categories, :id, :pretty_name, {:include_blank => 'None'}, {multiple: true, size: @categories.size+1} %>
		<span class="help-block">This controls which category contains the item. You can manage the <%= link_to "category list", admin_categories_path %> separately. Leave the category blank to turn the item into a promoted item that acts like a category itself on the menu bar. Hold the ctrl/cmd key while selecting names to choose more than one.</span>
  </div>
  <div class="field form-group">
    <%= f.label :image, class: "control-label"  %><br/>
    <% if @item.image? %>
			<%= image_tag(@item.image_url(:thumb)) %><br/>
    	<%= f.check_box :remove_image %> <%= f.label :remove_image, "Remove Current Image" %><br/>
		<% end %>
    <%= f.file_field :image %>
    <p class="help-block">This image is used in thumbnail format as the preview on the main page, and in full size once the item has been selected. Use the browse button to find a new image for this item.</p>
  </div>
  <div class="field form-group">
	<%= f.label :featured_item, class: "control-label" %><br/>
	<%= f.check_box :featured %> 
    <p class="help-block">Should this item be featured as a banner on the main page?</p>	
	</div>
  <div class="field form-group">
    <%= f.label :preview, class: "control-label"  %><br/>
    <%= f.bootsy_area :preview, editor_options: {html: true}, size: "100x12", class: "form-control" %>
    <span class="help-block">The preview is a small block of text that shows up in preview contexts and as the header image when an item is selected.</span>
  </div>
  <div class="field form-group">
    <%= f.label :body, class: "control-label"  %><br/>
    <%= f.bootsy_area :body, editor_options: {html: true}, size: "100x12", class: "form-control" %>
		<span class="help-block">The body is the full text that shows up when an item has been fully selected. You can use the controls to style this content, and you can embed images.</span>
  </div>
	<div class="field form-group">
		<%= f.label :connections, class: "control-label"  %><br/>
		<%= f.collection_select :connected_ids, @connectable_items, :id, :short_name, {include_blank: "None"}, {multiple: true, size: 10}%>
		<span class="help-block">This controls links between items which appear in their main profile.</span>
	</div>
  <h3>Attached Media Files</h3>
    <p class="help-block">You can upload related files here. They will automatically be sorted into appropriate categories on the front-end. Videos will be played on the site, while other file formats (e.g. PDF) will be linked in the media carousel for browsers to download.</p>
	<%= f.fields_for :attachments do |attachment_form|  %>
	<h4>Attachment</h4>
		  <p>
		  <%= attachment_form.label :file %><br />
			<%= link_to attachment_form.object.file.file.filename, attachment_form.object.file.url if attachment_form.object.file? %><br/>
		  <%= attachment_form.link_to_remove remove_link_html("Remove this attachment") %>		
		  <%= attachment_form.file_field :file %>	
		  </p>
	    <p>
	    <%= attachment_form.label :description %><br />
	    <%= attachment_form.bootsy_area :description, editor_options: {html: true}, size: "100x12", class: "form-control" %>
	    </p>
	  <% end %>
		<p style="margin-top: 20px;"><%= f.link_to_add add_link_html("Add new media attachment"), :attachments %></p>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<h1>Editing a Moving Stories web item</h1>

<%= render 'form' %>

<%= link_to back_link_html("Return to item listing"), admin_items_path %>

app/views/admin/items/index.html.erb
<h1>Listing web items</h1>

<table class="table table-hover">
  <thead>
    <tr>
	    <th colspan="2"></th>
      <th>Name</th>
			<th>Categories</th>
      <th>Preview Text</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
	      <td><%= link_to edit_link_html, [:edit, :admin, item] %></td>
        <td><%= link_to remove_link_html, [:admin, item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td style="width:1%; white-space:nowrap;"><%= link_to truncate(item.name, length: 45, omission: "..."), item_path(item) %></td>
				<td><% unless item.categories.empty? %><%= item.categories.map{|category| category.name }.join(", ")%><% else %>NO CATEGORIES (Promoted Item)<% end %></td>
        <td><%= truncate(item.preview, length: 90, omission: "...") %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to add_link_html("Create new item"), new_admin_item_path %><br/>
<%= link_to back_link_html("Return to dashboard"), admin_path %>

app/views/admin/items/new.html.erb
<h1>Add a new web item to Moving Stories</h1>

<%= render 'form' %>

<%= link_to back_link_html("Return to item listing"), admin_items_path %>

app/views/admin/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @item.body %>
</p>

<p>
  <strong>Preview:</strong>
  <%= @item.preview %>
</p>

<%= link_to edit_link_html("Edit this item"), [:edit, :admin, @item] %> |
<%= link_to back_link_html("Back to items listing"), admin_items_path %>