config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#main'
  get 'main' => 'pages#main'
  get 'pages/change_subnav'
  get 'pages/change_focus'  
  resources :sessions, only: [:new, :create, :destroy]
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get '/items/:id', to: 'items#show', as: 'item'
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
    resources :users    
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items, :dependent => :nullify
  belongs_to :category
  has_many :categories, :dependent => :nullify
  validates :name, presence: true
  
  def pretty_name
    if category
      return "-- #{name}"
    else
      return name
    end
  end
  
  def top_level?
    category.nil?
  end
  
  def self.find_all_top_level
    Category.where('category' => nil).order(position: :asc, name: :asc)
  end
  
  def self.find_all_children id
    Category.where('category_id' => id).order(position: :asc, name: :asc)
  end
  
  def self.find_all_nested
    cats = []
    all_cats = Category.find_all_top_level
    all_cats.each do |cat|
      cats << cat
      Category.find_all_children(cat.id).each do |subcat|
        cats << subcat
      end
    end
    return cats
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :logged_in?
  layout 'admin'
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.find_all_top_level.order("name")
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @top_level_categories = Category.find_all_top_level
  end

  # GET /categories/1/edit
  def edit
    @top_level_categories = Category.find_all_top_level
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @top_level_categories = Category.find_all_top_level
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: [:admin,@category] }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    @top_level_categories = Category.find_all_top_level    
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin,@category] }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id, :position)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field form-group">
    <%= f.label :name, class: "control-label" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
	<div class="field form-group">
	  <%= f.label :position, class: "control-label" %><br>
		<%= f.select :position, options_for_select(1..Category.count+1, @category.position) %>
	</div>
  <div class="field form-group">
		<%= f.label :category, class: "control-label"  %><br/>
		<%= f.collection_select :category_id, @top_level_categories, :id, :name, {include_blank: true} %>
		<span class="help-block">This controls which top-level category contains the category. Only use this to produce a hierarchy of categories, such as "Grad Students"", which belong to "People".</span>
	</div>		
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to back_link_html("Return to category listing"), admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>
<p><em>These are the categories that items can belong to.</em></p>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to edit_link_html, [:edit, :admin, category] %> <%= link_to remove_link_html, [:admin, category], method: :delete, data: { confirm: 'Are you sure?' }%> <%= category.name %> (Position: <%= category.position %>)</td>
      </tr>
			<% category.categories.each do |subcat| %>
				<tr>
					<td>-- <%= link_to edit_link_html, [:edit, :admin, subcat] %> <%= link_to remove_link_html, [:admin, subcat], method: :delete, data: { confirm: 'Are you sure? This will turn any remaining items with this category into PROMOTED items on the menu' }%> <%= subcat.name %> (Position: <%= subcat.position %>)</td>
				</tr>
			<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to add_link_html("Create new category"), new_admin_category_path %><br/>
<%= link_to back_link_html("Return to dashboard"), admin_path %>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to back_link_html("Return to category listing"), admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<%= link_to 'Edit', [:edit, :admin, @category] %> |
<%= link_to 'Back', admin_categories_path %>