config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#main'
  get 'main' => 'pages#main'
  get 'pages/change_subnav'
  get 'pages/change_focus'  
  resources :sessions, only: [:new, :create, :destroy]
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get '/items/:id', to: 'items#show', as: 'item'
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
    resources :users    
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9\-.]/    
  VALID_PASSWORD_REGEX = /((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})/
  PASSWORD_REQUIREMENTS = "must: contain a digit from 0-9, one lowercase character, one uppercase character, one special symbol in the list '@#$%', and have a length of at least 6 characters and a maximum of 20 characters."
  # users.password_hash in the database is a :string
  include BCrypt

  attr_accessor :password, :password_confirmation # this is needed to use password and password confirmation virtually
  # We need to validate that the user has typed the same password twice
  # but we only want to do the validation if they've opted to change their password.
  validates_confirmation_of :password, if: lambda{ new_record? || password_changed? }

  before_save :hash_new_password, if: lambda{ new_record? || password_changed? }
  before_save { self.email = email.downcase }
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }, if: :email  
  validates :password, presence: true,
                       format: { with: VALID_PASSWORD_REGEX, message: PASSWORD_REQUIREMENTS }, if: lambda{ new_record? || password_changed? }
                         
  # As is the 'standard' with rails apps we'll return the user record if the
  # password is correct and nil if it isn't.
  def self.authenticate(email, password)
    # Because we use bcrypt we can't do this query in one part, first
    # we need to fetch the potential user
    if user = find_by_email(email)
    # Then compare the provided password against the hashed one in the db.
      if BCrypt::Password.new(user.hashed_password).is_password? password
        # If they match we return the user 
        return user
      end
    end
    # If we get here it means either there's no user with that email, or the wrong
    # password was provided.  But we don't want to let an attacker know which. 
    return nil
  end
  
  private
  # This is where the real work is done, store the BCrypt has in the
  # database
  def hash_new_password
    self.hashed_password = BCrypt::Password.create(@password)
  end
  
  # By default the form_helpers will set new_password to "",
  # we don't want to go saving this as a password
  def password_changed?
    !@password.nil?
  end  
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :logged_in?
  layout 'admin'  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
      
  # assign them a random one and mail it to them, asking them to change it
   def forgot_password
     @user = User.find_by_email(params[:email])
     random_password = Array.new(10).map { (65 + rand(58)).chr }.join
     random_password += "1$" # stupid kludge to make it accepted by the acceptable password regex
     @user.password = @user.password_confirmation = random_password
     @user.save!
     Mailer.forgot_password(@user, @user.alias, random_password).deliver
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user], :html => { role: "form"}) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field form-group">
    <%= f.label :email, class: "control-label" %>
    <%= f.text_field :email, size: 100, class: "form-control", placeholder: "Enter email", required: "required" %>
  </div>
  <div class="field form-group">
    <%= f.label :password, class: "control-label" %>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
		<span class="help-block">The password must: contain a digit from 0-9, one lowercase character, one uppercase character, one special symbol in the list '@#$%', and have a length of at least 6 characters and a maximum of 20 characters.</span>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation, class: "control-label" %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repeat the password" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing Moving Stories admin user account</h1>

<%= render 'form' %>

<%= link_to back_link_html("Return to user listing"), admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to raw("<span class='glyphicon glyphicon-edit'></span>"), [:edit, :admin, user] %> <%= link_to raw("<span class='glyphicon glyphicon-trash'></span>"), [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %> <%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to add_link_html("Add new user"), new_admin_user_path %><br/>
<%= link_to back_link_html("Return to dashboard"), admin_path %>

app/views/admin/users/new.html.erb
<h1>Create a new Moving Stories admin account</h1>

<%= render 'form' %>

<%= link_to back_link_html("Return to user listing"), admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', [:edit, :admin, @user] %> |
<%= link_to 'Back', admin_users_path %>