config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#main'
  get 'main' => 'pages#main'
  get 'pages/change_subnav'
  get 'pages/change_focus'  
  resources :sessions, only: [:new, :create, :destroy]
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get '/items/:id', to: 'items#show', as: 'item'
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items
    resources :categories
    resources :users    
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

end

app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Moving Stories</a>
    </div>
  </div>
</header>

app/views/layouts/_big_carousel.html.erb
<div id="main-carousel" class="carousel slide" data-ride="carousel"><!-- class of slide for animation -->
  <div class="carousel-inner">
		<% @banner_items.each_with_index do |banner, i| %>
			<div class="<%= " active" if i.zero? %>"> <!-- item class makes it disappear but is needed so get it back-->
				<% image_tag(banner.image_url(:banner)) if banner.image? %><img src="http://placehold.it/1800x400/000000/ffffff" height="400" width="1800"/>
				<div class="carousel-caption"><% banner.name %>Test carousel</div>								
			</div>
		<% end %>									
  </div>
	<ol class="carousel-indicators">
		<% @banner_items.each_with_index do |banner, i| %>
			<li data-target="#main-carousel-<%=banner.id%>" data-slide-to="<%= i %>" class="<%= "active" if i.zero? %>"></li>
		<% end %>
	</ol>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
	<p class="text-muted credit">Funding & support by:
		<a href="http://www.siat.sfu.ca" target="_blank"><%= image_tag("logosiat.png", size: "68x32", alt: "SIAT logo") %></a>
		<a href="http://www.sfu.ca" target="_blank"><%= image_tag("logosfu.png", size: "59x32", alt: "SFU logo") %></a>
		<a href="http://www.fcat.sfu.ca/" target="_blank"><%= image_tag("fcattrans.png", size: "68x32", alt: "FCAT logo") %></a>
		<a href="http://www.sshrc-crsh.gc.ca/" target="_blank"><%= image_tag("logosshrc.png", size: "383x32", alt: "SSHRC logo") %></a>
		<a href="http://www.mitacs.ca/" target="_blank"><%= image_tag("mtacstrans.png", size: "68x32", alt: "MITACS logo") %></a></p>
    <p class="text-muted">&copy; Moving Stories 2012 - <%= Time.now.strftime("%Y") %> All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container-fluid logo-block">
<%= image_tag("mslogo_01.png", height: "120", alt: "Moving Stories project logo", title: "Moving Stories project logo")%>
	<span class="pull-right social-media"><%= mail_to "admin@movingstories.ca", raw('<i class="fa fa-envelope fa-3x"></i>') %> <a href="https://www.facebook.com/groups/430082843697624/"><i class="fa fa-facebook fa-3x"></a></i> <a href="https://twitter.com/Moving_Stories"><i class="fa fa-twitter fa-3x"></i></a></span>
</div>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
	    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
		</div>
		<div class="collapse navbar-collapse" id="navbarCollapse">
	    <ul class="nav navbar-nav nav-items">
	      <li class="active"><a href="#" data-filter="<%= home_category %>" class="nav_elem" id="home-nav">Home</a></li>
				<% @promoted_items.each do |item| %>
					<li><a href="#" class="nav_elem promoted" data-item-id="<%= item.id %>"><%= item.name %></a></li>
				<% end %>
	      <% @categories.each do |category| %>
					<li><a href="#" data-filter=".category<%=category.id%>" data-id="<%=category.id%>" class="nav_elem"><%= category.name %></a></li>
				<% end %>
	    </ul>
	  	<form class="navbar-form navbar-right" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search" id="search" name="search"/>
		      </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	    </form>
			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">
            <span class="glyphicon glyphicon-user"></span> <%= current_user.email %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu">
						<li><%= link_to link_html("dashboard", "Dashboard"), "/admin" %></li>
            <li class="divider"></li>
            <li><%= link_to link_html("log-out", "Logout"), log_out_path %></li>
          </ul>
        </li>
				<% else %>
					<li class="dropdown">
						<%= link_to login_link_html("Login"), log_in_path %>
					</li>
				<% end %>
      </ul>	
    </div>
		<div class="collapse navbar-collapse secondary container-fluid" id="subnavbar">
			<%= render "layouts/secondary_nav"%>
		</div>
</nav>

app/views/layouts/_secondary_nav.html.erb
<% unless @sub_categories.blank? %>
  <ul class="nav navbar-nav nav-items">
    <li><a href="#" data-filter="<% if @category %>.category<%=@category.id%><%else%><%= home_category %><%end%>" class="subnav_elem">All</a></li>
    <% @sub_categories.each do |category| %>
			<li><a href="#" data-filter=".category<%=category.id%>" class="subnav_elem"><%= category.name %></a></li>
		<% end %>
  </ul>
<script>
// controls the filtering
$('.subnav_elem').bind("click", function(){
	var selector = $(this).attr('data-filter');
	$('#isotope').isotope({ 
	filter: selector,
	animationOptions: {
		duration: 750,
   		easing: 'linear',
   		queue: false,
	}
	});
	return false;
});

$('.subnav_elem').bind("click", function(e) {

    $('.active').removeClass('active');

    var $parent = $(this).parent();
    if (!$parent.hasClass('active')) {
        $parent.addClass('active');
    }
    e.preventDefault();
});
</script>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'nested_form', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="container">
	<%= render 'layouts/admin_header' %>
	<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">	
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container-fluid">
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>